### ISSUE TITLE
 Fatal error: Uncaught Error: fread(): Argument #2 ($length) must be greater than 0

### ISSUE THREAD

**Issue by Tanguy-Magnaudet** [polylang/dynamo#30] opened 2023-07-24 16:13 UTC
php v8.2.7
DynaMo v1.1
WordPress v6.2.2
WPML v4.6.4
WPML String Translation v3.2.6
Advanced Custom Fields Multilingual v2.0.5
ACF Pro v6.1.7

After translating a field attached to a User Profil Form, got the same error than #23.

Here is the .zip of the .mo file.

[acf-field-group-5792-en_US.mo.zip](https://github.com/polylang/dynamo/files/12147882/acf-field-group-5792-en_US.mo.zip)

**Comment by Chouby** [comment] 2023-07-26 14:10
Thank you for your bug report.
I examined your mo file and I confirm that this is exactly the same issue as #23, caused by WPML creating MO files without headers. This will be fixed in version 1.2 that I plan to release soon.

**Closed by Chouby** 2023-07-26 14:10 UTC
Labels: duplicate
